# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__,np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baselin

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
n=np.zeros((3,4))
print(n.size*n.itemsize)

96


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [4]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [5]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [6]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [7]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [10]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [11]:
a=np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [12]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [14]:
z=np.random.uniform((3,3,3))
print(z)

[1.3747724  2.96378421 1.58638365]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [15]:
z=np.random.random((10,10))
zmin,zmax=z.min(),z.max()
print(zmin,zmax)

0.003042322777680573 0.9948095755534831


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [17]:
z=np.random.random(30)
m=z.mean()
print(m)

0.5684539612713725


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [19]:
z=np.ones((10,10))
z[1:-1, 1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [24]:
z=np.ones((10,10))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [25]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [26]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [31]:
z=np.zeros((8,8))
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [32]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [10]:
array=np.array([[0,1],[1,0]])
z=np.tile(array,(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [13]:
z=np.random.random((5,5))
zmax,zmin=z.max(),z.min()
z=(z-zmin)/(zmax-zmin)
print(z)

[[0.8045662  0.16015762 0.09850206 0.77536419 0.70702926]
 [0.47595996 0.99259318 0.75896817 0.14516683 0.5556804 ]
 [0.90442822 0.43838294 0.38012284 0.67850017 0.15166261]
 [0.81849838 0.69361373 0.35114594 0.33209351 0.88774322]
 [0.21436864 0.         0.35702129 1.         0.4574727 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [15]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\Dell\AppData\Local\Temp\ipykernel_12600\889307967.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [16]:
z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [19]:
z=np.arange(11)
z[(3<z)&(z<=8)]*=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [20]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [21]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [22]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Dell\AppData\Local\Temp\ipykernel_12600\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Dell\AppData\Local\Temp\ipykernel_12600\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [26]:
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[ 3. -5. -7.  6. -8. -4.  4. -6. -8. -5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [27]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[0 4 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [28]:
defaults=np.seterr(all="ignore")
z=np.ones(1)/0
_=np.seterr(**defaults)
with np.errstate(divide="ignore"):
    z=np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [29]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Dell\AppData\Local\Temp\ipykernel_12600\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [30]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [33]:
z=np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [4]:
a=np.ones(3)*1
b=np.ones(3)*2
c=np.ones(3)*3
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [5]:
z=np.random.uniform(0,10,10)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[6. 6. 9. 1. 8. 4. 9. 8. 9. 6.]
[6. 6. 9. 1. 8. 4. 9. 8. 9. 6.]
[6. 6. 9. 1. 8. 4. 9. 8. 9. 6.]
[6 6 9 1 8 4 9 8 9 6]
[6. 6. 9. 1. 8. 4. 9. 8. 9. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [6]:
z=np.zeros((5,5))
z=z+np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [7]:
def generator():
    for x in range(10):
        yield x
z=np.fromiter(generator(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [8]:
z=np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [9]:
z=np.random.random(10)
z.sort()
print(z)

[0.0412816  0.0743496  0.14873576 0.23370861 0.25726583 0.42583787
 0.44684446 0.4736289  0.55615401 0.5925902 ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [11]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [12]:
d=np.random.randint(0,2,5)
e=np.random.randint(0,2,5)
equal=np.allclose(d,e)
print(equal)
equal=np.array_equal(d,e)
print(equal)


False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [15]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [16]:
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.93236689 0.54823401 0.69056138 0.84365039 1.05520656 0.87389326
 0.57465546 0.39325142 1.01229795 0.47175823]
[0.53796234 1.55740565 1.34868582 0.40698892 0.69115521 0.99667571
 1.26856329 1.5269935  1.18826749 1.38816298]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [17]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)

[0.63202287 0.         0.2622863  0.40473674 0.15648721 0.37521326
 0.79047373 0.14654639 0.89160666 0.38924767]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [3]:
z=np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [5]:
x=np.arange(8)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [6]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:   
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [13]:
s=np.arange(100)
np.set_printoptions(threshold=np.inf)
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [14]:
z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(z-v)).argmin()
print(z[index])

91


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [15]:
z=np.zeros(10,[('position',[('x',float,1),
                           ('y',float,1)]),
              ('color',[('r',float,1),
                       ('g',float,1),
                       ('b',float,1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Dell\AppData\Local\Temp\ipykernel_14108\3137944455.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z=np.zeros(10,[('position',[('x',float,1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [18]:
z=np.random.random((10,2))
x,y=np.atleast_2d(z[:,0],z[:,1])
d=np.sqrt((x-x.T)**2+(y-y.T)**2)
print(d)


[[0.         0.59031753 0.57902034 0.29511314 0.46098822 0.63703103
  0.15219127 0.83260765 0.24814142 0.34556914]
 [0.59031753 0.         0.22108553 0.32999549 0.82406773 0.27852808
  0.58464843 0.3471116  0.61713199 0.50369417]
 [0.57902034 0.22108553 0.         0.28409113 0.92120759 0.0725122
  0.51653073 0.25411244 0.51400551 0.36504812]
 [0.29511314 0.32999549 0.28409113 0.         0.66882984 0.34446001
  0.25586616 0.53749484 0.29033932 0.21387511]
 [0.46098822 0.82406773 0.92120759 0.66882984 0.         0.9915608
  0.61302488 1.1503576  0.70798961 0.79557122]
 [0.63703103 0.27852808 0.0725122  0.34446001 0.9915608  0.
  0.56264483 0.20748556 0.54932146 0.39208714]
 [0.15219127 0.58464843 0.51653073 0.25586616 0.61302488 0.56264483
  0.         0.76796819 0.09682718 0.21244237]
 [0.83260765 0.3471116  0.25411244 0.53749484 1.1503576  0.20748556
  0.76796819 0.         0.75680597 0.59887396]
 [0.24814142 0.61713199 0.51400551 0.29033932 0.70798961 0.54932146
  0.09682718 0.7568059

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [19]:
z=np.arange(10,dtype=np.int32)
z=z.astype(np.float32,copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [21]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z=np.genfromtxt(s,delimiter=",",dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Dell\AppData\Local\Temp\ipykernel_14108\4061963046.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z=np.genfromtxt(s,delimiter=",",dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [14]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [15]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [16]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [23]:
x=np.random.rand(5,10)
y=x-x.mean(axis=1,keepdims=True)
print(y)

[[-0.45290141  0.43926675 -0.31466547 -0.01934171  0.05154912  0.27488484
   0.24740497 -0.47342445  0.23725038  0.00997699]
 [-0.43550484  0.44403088 -0.23263566 -0.3608299   0.39112761 -0.0534493
   0.085579    0.09082864  0.16838602 -0.09753246]
 [-0.01770549 -0.27745672 -0.19011926 -0.14290945 -0.06518664 -0.25471852
   0.34051931  0.49614903  0.36872256 -0.25729484]
 [ 0.17213208  0.5039106  -0.20151205 -0.37489447 -0.37380179  0.33790011
   0.12262625 -0.23963893  0.23731601 -0.18403783]
 [ 0.17551209 -0.01705211  0.09369957 -0.1423792   0.13788579  0.25485907
  -0.44128631  0.4027352  -0.49004235  0.02606825]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [22]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[1 7 5]
 [0 0 0]
 [3 1 2]]
[[0 0 0]
 [3 1 2]
 [1 7 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [16]:
z=np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [17]:
z=np.random.uniform(0,1,10)
n=0.5
m=z.flat[np.abs(z-n).argmin()]
print(m)

0.4995245814040695


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [2]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [3]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [4]:
z=np.ones(10)
i=np.random.randint(0,len(z),20)
z+=np.bincount(i,minlength=len(z))
print(z)

[3. 2. 3. 5. 4. 2. 3. 2. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [5]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [6]:
w,h=16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [7]:
A=np.random.randint(0,10,(3,4,3,4))
sum=A.sum(axis=(-2,-1))
print(sum)

[[59 52 70 58]
 [61 57 60 58]
 [53 37 49 39]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [9]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)



[0.51557466 0.38939339 0.47511899 0.54638651 0.47423111 0.61697823
 0.5667315  0.45954182 0.46326979 0.64782297]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [10]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A,B))

array([0.96754941, 1.92411276, 1.16643566, 0.37554779, 1.24229862])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [12]:
z=np.array([1,2,3,4,5])
nz=3
Z0=np.zeros(len(z)+len(z)-1*(nz))
Z0[::nz+1]=z
print(Z0)

ValueError: could not broadcast input array from shape (5,) into shape (2,)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [13]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [3]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [5]:
faces=np.random.randint(0,100,(10,3))
f=np.roll(faces.repeat(2,axis=1),-1,axis=1)
f=f.reshape(len(f)*3,2)
f=np.sort(f,axis=1)
g=f.view(dtype=[('p0',f.dtype),('p1',f.dtype)])
g=np.unique(g)
print(g)

[( 0,  4) ( 0, 15) ( 3, 12) ( 3, 14) ( 4, 15) ( 5, 36) ( 5, 97) (12, 14)
 (14, 43) (14, 82) (17, 46) (17, 83) (25, 36) (25, 39) (28, 95) (28, 96)
 (29, 47) (29, 76) (36, 39) (36, 57) (36, 90) (36, 97) (43, 82) (46, 83)
 (47, 76) (57, 90) (66, 87) (66, 95) (87, 95) (95, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [6]:
c=np.bincount([1,1,2,3,4,4,6])
a=np.repeat(np.arange(len(c)),c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [7]:
def moving_average(a,n=3):
    ret=np.cumsum(a,dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [8]:
from numpy.lib import stride_tricks
def rolling(a,window):
    shape=(a.size-window+1,window)
    strides=(a.itemsize,a.itemsize)
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
z=rolling(np.arange(10),3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [9]:
z=np.random.randint(0,2,100)
np.logical_not(z,out=z)
z=np.random.uniform(-1.0,1.0,100)
np.negative(z,out=z)

array([ 0.81371358, -0.58845772, -0.81133308, -0.16085107, -0.62221548,
        0.82788204, -0.99398343, -0.91792329,  0.24430272,  0.57602511,
       -0.22055472, -0.7466613 , -0.87200494,  0.54015569, -0.46812038,
        0.58054893, -0.0992143 ,  0.39878615,  0.84690421,  0.35481706,
        0.89605201, -0.73829483,  0.7244421 , -0.03491638,  0.50819038,
       -0.67169755,  0.82173601,  0.55448474, -0.81569084,  0.83970029,
       -0.93112729, -0.84696201,  0.00827153, -0.47828771, -0.3191864 ,
        0.94480353,  0.8476197 ,  0.94885707,  0.41324916, -0.00245197,
       -0.86759958, -0.54000307, -0.79649356,  0.62365336,  0.26927751,
        0.76502934,  0.85080942,  0.54422167,  0.42741242,  0.19949361,
       -0.6272237 , -0.21027778,  0.43488142,  0.51938227, -0.30302958,
       -0.60754961,  0.55159057, -0.9132622 ,  0.60371937,  0.58988619,
       -0.81828682,  0.80987058, -0.60664139, -0.16319041,  0.5355007 ,
       -0.84801364,  0.01091602,  0.37705946,  0.05358482,  0.07

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [10]:
def distance(P0,P1,p):
    T=P1-P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[4.44275179 6.87048012 9.62746337 9.40780583 3.43608106 7.3449759
 3.0730583  8.64163377 1.35789189 2.70724008]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [11]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.12231241  5.90540523  0.94918376  6.15381304  3.05071946  0.65114991
   0.84437769  5.04504831  0.45384406  9.26508496]
 [ 8.593736    6.46698632  7.02387655  2.72140624  7.94482734  8.66190001
   7.27296492  3.565071    2.81241482  0.95787584]
 [ 8.07713809  0.64401778  1.53337537  1.63632348  2.1190352   9.52631642
   1.9272261   0.15155461  7.44180552  4.86527511]
 [ 3.51799596 13.39612759  5.41422987  8.86707915  8.51535644  4.25304267
   4.95085492  4.53358321  8.14859813  7.95405097]
 [ 7.18955918  1.84593391  2.03051164  0.85411458  2.82452785  8.4193168
   2.35228079  0.09386853  6.06032237  4.9685412 ]
 [ 0.12104817 10.64569557  5.30544945  5.44980071  7.70473342  0.21803154
   5.07527603  2.43552215  4.29838975  6.24633774]
 [ 0.08273743  7.27903911  2.29761549  5.81365648  4.46660357  0.52492798
   2.16219103  4.16031613  1.51027634  8.26721093]
 [ 2.44084536  3.14743196  0.14530361  3.82610323  1.69504941  3.68304482
   0.22824675  3.97881943  2.94172217  8.54635191]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [12]:
Z=np.random.randint(0,10,(10,10))
shape=(5,5)
fill=0
position=(1,1)

R=np.ones(shape,dtype=z.dtype)*fill
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
Zs=np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 2 1 8 7 4 5 6 8 4]
 [1 4 6 3 5 5 9 9 4 8]
 [0 0 6 5 0 5 7 3 2 5]
 [7 8 9 5 1 3 5 2 6 4]
 [0 2 0 1 5 3 0 7 4 0]
 [0 5 7 8 2 1 0 4 4 9]
 [4 4 2 0 3 0 6 2 1 7]
 [3 4 7 1 5 5 5 5 0 1]
 [9 9 2 0 7 4 2 3 7 6]
 [3 4 2 5 6 0 3 2 6 3]]
[[0. 0. 0. 0. 0.]
 [0. 3. 2. 1. 8.]
 [0. 1. 4. 6. 3.]
 [0. 0. 0. 6. 5.]
 [0. 7. 8. 9. 5.]]


C:\Users\Dell\AppData\Local\Temp\ipykernel_10400\3392324745.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [13]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [4]:
z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(z)
rank=np,sum(S>1e-10)
print(rank)

(<module 'numpy' from 'C:\\Users\\Dell\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>, 10)


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [5]:
z=np.random.randint(0,10,50)
print(np.bincount(z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [8]:
z=np.random.randint(0,5,(10,10))
n=3
i=1+(z.shape[0]-3)
j=1+(z.shape[1]-3)
c=stride_tricks.as_strided(z,shape=(i,j,n,n),strides=z.strides+z.strides)
print(c)

NameError: name 'stride_tricks' is not defined

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [13]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  4  7  6  2]
 [ 4  0  6  8 13]
 [ 7  6  4 42 10]
 [ 6  8 42  8 16]
 [ 2 13 10 16  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [14]:
p,n=10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [15]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [16]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [17]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z[np.argsort(Z)[-n:]])
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [18]:
def cartesian(arrays):
    arrays=[np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [19]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [6]:
x = np.random.rand()

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i,i',x,x,x)

3.2 µs ± 342 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
151 ns ± 3.08 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [7]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [15]:
Z = np.random.randint(0,5,(10,3))
print(Z)

[[3 0 2]
 [0 4 2]
 [2 2 0]
 [1 2 0]
 [0 1 3]
 [1 4 2]
 [4 0 4]
 [3 1 1]
 [1 1 2]
 [3 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [18]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [19]:
z=np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 3]
 [0 4 2]
 [1 1 2]
 [1 2 0]
 [1 4 2]
 [2 2 0]
 [3 0 2]
 [3 1 1]
 [3 2 0]
 [4 0 4]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [20]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.35030394, 0.03841734, 0.18856714, 0.04106114, 0.26440945,
        0.323228  , 0.08533576, 0.22672594, 0.09529936, 0.15711483],
       [0.77506177, 0.08499994, 0.4172125 , 0.09084945, 0.58501672,
        0.71515516, 0.18880885, 0.5016404 , 0.21085372, 0.34762298],
       [0.20270753, 0.02223065, 0.10911662, 0.02376052, 0.15300367,
        0.18703972, 0.04938055, 0.13119766, 0.05514611, 0.09091636],
       [0.02926191, 0.00320911, 0.01575157, 0.00342996, 0.0220869 ,
        0.02700018, 0.00712835, 0.01893908, 0.00796063, 0.01312426],
       [0.3630732 , 0.03981773, 0.19544078, 0.0425579 , 0.2740477 ,
        0.3350103 , 0.08844641, 0.23499054, 0.09877321, 0.16284197],
       [0.14834086, 0.01626833, 0.07985126, 0.01738789, 0.1119677 ,
        0.1368752 , 0.03613656, 0.09601011, 0.04035578, 0.06653237],
       [0.76029381, 0.08338036, 0.40926297, 0.08911841, 0.57386986,
        0.70152866, 0.1852113 , 0.49208219, 0.20683613, 0.3409994 ],
       [0.13233979, 0.01451352, 0.0712379

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [21]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [22]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [23]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.36249344  0.00919945]
